meta_product_name: "AIcrowd"
meta_title: "AIcrowd"
meta_description: "Crowdsourcing AI to solve real-world problems"
meta_image: "misc/new-aicrowd-head.jpg"
twitter_account: "@aicrowdHQ" # required for Twitter Cards
